### ISSUE TITLE
Are you aware of DEFTYPE?

### ISSUE THREAD

**Issue by Hexstream** [digikar99/extensible-compound-types#1]
http://www.lispworks.com/documentation/HyperSpec/Body/m_deftp.htm#deftype

**Comment by digikar99** [comment]
Yes, I am, and I do not see how one could implement the examples given in the README using `cl:deftype`*: one is the [`(integer-multiples integer)` type](https://github.com/digikar99/extensible-compound-types#example-code), and another is a [`(pair &optional type-a type-b)` type](https://github.com/digikar99/extensible-compound-types#parametric-types).

One more example would be a `type=` type:

```lisp
(defpackage extensible-compound-types-demo
  (:use :extensible-compound-types-cl))

(in-package :extensible-compound-types-demo)

(define-compound-type type= (object type-specifier)
  "This is the set of all types for which (TYPE= OBJECT TYPE-SPECIFIER) returns non-NIL."
  (and (or (symbolp object)
           (listp object))
       (type= object type-specifier)))

(typep 'single-float '(type= single-float)) ;=> T
(typep 'double-float '(type= single-float))

;; Define an alias for SINGLE-FLOAT
(deftype f32 () 'single-float)
;; don't know how to compare cleanly with CL:DEFTYPE
(typep 'f32 '(type= single-float)) ;=> T


(typep '(integer 0 3) '(type= (integer 0 3))) ;=> T

;; don't know how to compare cleanly with CL:DEFTYPE
(typep '(unsigned-byte 2) '(type= (integer 0 3))) ;=> T
```



*One possible way is to use `satisfies` but you will need one named function for *every* combination of parameters.

**Comment by Hexstream** [comment]
Ok, well I don't immediately understand the use-cases, but I think the
documentation should probably mention DEFTYPE and why it's (allegedly) not
good enough.

**Comment by digikar99** [comment]
Hmm, good point! I could further simplify the introduction. Currently:

> However, CLHS does not provide facilities for cleanly defining user-defined compound-types. Such types could include a (EQUALP OBJECT) type, a (TYPE= TYPE), or a (PAIR TYPE-1 TYPE-2) type, or (CUSTOM-ARRAY ELEMENT-TYPE DIMENSIONS). The most one can do is play around with SATISFIES types. However, not only do SATISFIES types not integrate well into rest of the type system, but they are restricted to single argument functions that only take the object to be type-checked as their argument.

Is the following more understandable?

> However, CLHS does not provide facilities for cleanly defining user-defined compound-types. Such types could include a (EQUALP OBJECT) type, a (TYPE= TYPE), or a (PAIR TYPE-1 TYPE-2) type, or (CUSTOM-ARRAY ELEMENT-TYPE DIMENSIONS). 

> While it might seem like CL:DEFTYPE allows for the definition of compound types, these types are merely abbreviations for existing type specifiers. The new types defined using CL:DEFTYPE are merely pre-specified combinations of existing types. The most one can do is play around with SATISFIES types. However, not only do SATISFIES types not integrate well into rest of the type system, but they are restricted to single argument functions that only take the object to be type-checked as their argument. See the [example-code](https://github.com/digikar99/extensible-compound-types#example-code) for an example of a type that is non-trivial (if not impossible!) to define using CL:DEFTYPE.

**Comment by Hexstream** [comment]
Slightly!

**Comment by digikar99** [comment]
Thanks for the feedback, hopefully this would be slightly better!
